/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppointmentModal: typeof import('./components/AppointmentModal.vue')['default']
    ChangelogDialog: typeof import('./components/ChangelogDialog.vue')['default']
    Chatbot: typeof import('./components/Chatbot.vue')['default']
    ChatbotButton: typeof import('./components/ChatbotButton.vue')['default']
    ConfirmationDialog: typeof import('./components/ConfirmationDialog.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IntegrationSettingsDialog: typeof import('./components/IntegrationSettingsDialog.vue')['default']
    Layout: typeof import('./components/Layout.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NewMessageModal: typeof import('./components/NewMessageModal.vue')['default']
    PhoneNumberInput: typeof import('./components/PhoneNumberInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TwoFactorSetupDialog: typeof import('./components/TwoFactorSetupDialog.vue')['default']
  }
}
